[build]
builder = "nixpacks"

[build.services.backend]
root = "backend"
buildCommand = "npm install"
startCommand = "node server.js"
internalPort = 8080
healthcheckPath = "/api/check-session"
healthcheckTimeout = 100

[build.services.frontend]
root = "frontend"
buildCommand = "npm install && npm run build"
startCommand = "npm start"
internalPort = 3000
healthcheckPath = "/"
healthcheckTimeout = 100
publicPort = 3000

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
